---
title: "README"
author: "PJKA"
date: "20/02/2020"
output: md_document
---

# carbulate

This package will calculate the carbonate species (CO2(aq), HCO3-, CO3--) concentrations from a measured DIC concentration, pH value, and temperature of your water sample. Values will be added onto the dataframe 'df' you supply.

## Parameters
carbulate(df, 'DIC_col_mg.L', 'pH_col', 'temp_col_C', 'pressure_kPa')

df - your dataframe that contains all the variables  
DIC_col_mg.L - Name of the column that contains the measured dissolved inorganic carbon concentration (mg C/L)  
pH_col - Name of column with your measured pH  
temp_col_C - Name of column with your measured water temperature (in Celsius)  
pressure_kPa - Name of column with the atmospheric pressure where the sample was collected from (in kPa)

## Example
This is how you would input this function to add the carbonate species to the dataframe 'water.df':  
water.df <- carbulate(water.df, 'DIC_mgC.L', 'pH', 'Temp_C', 'pressure_kPa')


## Calculations
Temperature dependent K values were calculated according to the following references:  

CO2 + H2O <=> HCO3- + H+ ; Harned & Davis Jr. 1943. Journal of the American Chemical Society 65 (10): p2030-2037.  

HCO3- <=> CO3-- + H+ ; Harned & Scholes Jr. 1941. Journal of the American Chemical Society 63 (6): p1706-1709.  

Solubility coefficient of CO2 in water (Henry's Law); Harned & Davis Jr. (1943) and as used in Venkiteswaran et al. 2014. PLoS ONE 9 (7): p22-25. doi: 10.1371/journal.pone.0101756.
